### ISSUE TITLE
Two asserts for the same input expect a different result.

### ISSUE THREAD

**Issue by enrico3** [oduvan/checkio-mission-acceptable-password-2#5]
The initial code includes two asserts for the same input 'muchlonger'. The first time it checks for 'True' and the second time it checks for 'False'. It should check for 'False' both times. The source code of the wrong assert does not seem to be part of this this repo however (I cannot find it).

![image](https://user-images.githubusercontent.com/31779179/197337221-f9f8fa0f-bf34-4278-89f7-c3ffb453963c.png)

**Comment by freemanlex** [comment]
everything is OK now
